In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Load the dataset
df = pd.read_csv('C:/Users/yasee/Downloads/GlobalWeatherRepository.csv')
df.head()

,country,location_name,latitude,longitude,timezone,last_updated_epoch,last_updated,temperature_celsius,temperature_fahrenheit,condition_text,...,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index,sunrise,sunset,moonrise,moonset,moon_phase,moon_illumination
0,Afghanistan,Kabul,34.52,69.18,Asia/Kabul,1715849100,2024-05-16 13:15,26.6,79.8,Partly Cloudy,...,8.4,26.6,1,1,04:50 AM,06:50 PM,12:12 PM,01:11 AM,Waxing Gibbous,55
1,Albania,Tirana,41.33,19.82,Europe/Tirane,1715849100,2024-05-16 10:45,19.0,66.2,Partly cloudy,...,1.1,2.0,1,1,05:21 AM,07:54 PM,12:58 PM,02:14 AM,Waxing Gibbous,55
2,Algeria,Algiers,36.76,3.05,Africa/Algiers,1715849100,2024-05-16 09:45,23.0,73.4,Sunny,...,10.4,18.4,1,1,05:40 AM,07:50 PM,01:15 PM,02:14 AM,Waxing Gibbous,55
3,Andorra,Andorra La Vella,42.50,1.52,Europe/Andorra,1715849100,2024-05-16 10:45,6.3,43.3,Light drizzle,...,0.7,0.9,1,1,06:31 AM,09:11 PM,02:12 PM,03:31 AM,Waxing Gibbous,55
4,Angola,Luanda,-8.84,13.23,Africa/Luanda,1715849100,2024-05-16 09:45,26.0,78.8,Partly cloudy,...,183.4,262.3,5,10,06:12 AM,05:55 PM,01:17 PM,12:38 AM,Waxing Gibbous,55

In [2]:
df.columns

Index(['country', 'location_name', 'latitude', 'longitude', 'timezone',
       'last_updated_epoch', 'last_updated', 'temperature_celsius',
       'temperature_fahrenheit', 'condition_text', 'wind_mph', 'wind_kph',
       'wind_degree', 'wind_direction', 'pressure_mb', 'pressure_in',
       'precip_mm', 'precip_in', 'humidity', 'cloud', 'feels_like_celsius',
       'feels_like_fahrenheit', 'visibility_km', 'visibility_miles',
       'uv_index', 'gust_mph', 'gust_kph', 'air_quality_Carbon_Monoxide',
       'air_quality_Ozone', 'air_quality_Nitrogen_dioxide',
       'air_quality_Sulphur_dioxide', 'air_quality_PM2.5', 'air_quality_PM10',
       'air_quality_us-epa-index', 'air_quality_gb-defra-index', 'sunrise',
       'sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'],
      dtype='object')

In [ ]:
df.head()

In [3]:
df.drop(columns = ['condition_text','country', 'location_name','latitude','longitude','timezone','last_updated_epoch','last_updated','temperature_fahrenheit', 'wind_mph','wind_direction','wind_degree', 'pressure_in','precip_in','feels_like_fahrenheit', 'visibility_miles', 'gust_kph', 'sunrise','sunset', 'moonrise', 'moonset', 'moon_phase', 'moon_illumination'], inplace=True)

In [4]:
df.head()

,temperature_celsius,wind_kph,pressure_mb,precip_mm,humidity,cloud,feels_like_celsius,visibility_km,uv_index,gust_mph,air_quality_Carbon_Monoxide,air_quality_Ozone,air_quality_Nitrogen_dioxide,air_quality_Sulphur_dioxide,air_quality_PM2.5,air_quality_PM10,air_quality_us-epa-index,air_quality_gb-defra-index
0,26.6,13.3,1012.0,0.0,24,30,25.3,10.0,7.0,9.5,277.0,103.0,1.1,0.2,8.4,26.6,1,1
1,19.0,11.2,1012.0,0.1,94,75,19.0,10.0,5.0,11.4,193.6,97.3,0.9,0.1,1.1,2.0,1,1
2,23.0,15.1,1011.0,0.0,29,0,24.6,10.0,5.0,13.9,540.7,12.2,65.1,13.4,10.4,18.4,1,1
3,6.3,11.9,1007.0,0.3,61,100,3.8,2.0,2.0,8.5,170.2,64.4,1.6,0.2,0.7,0.9,1,1
4,26.0,13.0,1011.0,0.0,89,50,28.7,10.0,8.0,12.5,2964.0,19.0,72.7,31.5,183.4,262.3,5,10

In [5]:
y = df['temperature_celsius']
X = df.drop(columns = ['temperature_celsius'])

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
def evaluate_model(model, X_train, y_train, X_test, y_test):
    # Fit the model
    model.fit(X_train, y_train)

    # Make predictions
    y_pred = model.predict(X_test)

    model.score(X_test, y_test)

    # Calculate metrics
    mse = mean_squared_error(y_test, y_pred)
    r2 = r2_score(y_test, y_pred)

    return mse, r2

In [7]:
from sklearn.ensemble import RandomForestRegressor
rf = RandomForestRegressor(n_estimators=100, random_state=42)

In [14]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

In [17]:
rf.score(X_test, y_test)

0.9948399008970218

In [17]:
from sklearn.linear_model import LinearRegression
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
y_pred_lin = lin_reg.predict(X_test)
lin_reg.score(X_test, y_test)

0.9599028378822254

In [8]:
from xgboost import XGBRegressor
xgb = XGBRegressor(n_estimators=100, random_state=42)

In [9]:
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)
xgb.score(X_test, y_test)

0.9948414508250129